GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWtzaGF5IiwiaWF0IjoxNjI2MTg1NjQ4LCJleHAiOjE2MjYxODU2ODh9.HGH4j61gHbJZeJKxCJVeRniqgCxyORkiY5lwf-olSUc

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWtzaGF5IiwiaWF0IjoxNjI2NzAxNTc5fQ.WeDGS8htQ5-0QdoXejfUcnJ3irQ8BzUlHMhfeHztZOw"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWtzaGF5IiwiaWF0IjoxNjI2NzAxNTc5fQ.WeDGS8htQ5-0QdoXejfUcnJ3irQ8BzUlHMhfeHztZOw"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "user_name":"Akshay"
}